# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false
org.gradle.user.home=C:\\Users\\varad\\AndroidStudioProjects\\v2\\.gradle-local
org.gradle.java.home=C:\\Users\\varad\\.jdks\\corretto-17.0.12
android.useAndroidX=true
android.nonTransitiveRClass=true
